--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync

# domain to which this site is deployed
base_url: http://mhlakhani.com

google_analytics:
  domain: mhlakhani.com
  site_id: UA-20351920-1

# currently used by logo
site_name: mhlakhani

# number of featured posts to display on front
featured_count: 5

# number of excerpted posts to display on front
excerpt_count: 5

# number of other articles to reference at bottom of each article
other_articles_max: 3

# Development mode
development: false

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: mhlakhani-blog
include_disqus_js: true
